### PR TITLE
fix: TabBar props can't be overridden

### PR DESCRIPTION
**Pull request by oureta**

### CODE REVIEW

**Comment by skv-headless** [comment]
How to reproduce that bug?

**Comment by dcworldwide** [comment]
So default props are not being respected if we have a custom tab bar? If so, LGTM, it explains why scrollWithoutAnimation={true} is not working for me

**Comment by oureta** [comment]
For example, I'm using `ScrollableTabBar` and I would like to hook into the `goToPage` prop:

```
renderTabBar={
  props => (
    <ScrollableTabBar goToPage={/* this will be overridden */} />
  )
}

```

**Comment by skv-headless** [comment]
onChangeTab is a method of scrollabe-tab-view. I haven't tried this code but seems that it breaks tab bar.

**Comment by oureta** [comment]
I need this so I would be able to override the behavior when navigating using the tabs (not from swiping).

**Comment by skv-headless** [comment]
You need hook in goToPage?
```<ScrollableTabView onChangeTab={() => {}}>``` what is wrong with that?
I can't accept your patch. It will break existing code.

**Comment by oureta** [comment]
How can you detect that the change/event has been triggered from tabs?

**Comment by oureta** [comment]
How can I detect that a tab has been pressed? For example, i would like to scroll to top on click of the current/same tab.

**Comment by skv-headless** [comment]
Just use custom tab bar

**Comment by oureta** [comment]
Ok. I'll just close this PR if you think this is not useful.

**Pull request closed without merging**
