### PR TITLE
next page not prerendered #341

### PR DESCRIPTION
**Pull request by cctuan**
related #341

### CODE REVIEW

**Comment by skv-headless** [comment]
Thanks 👍 But I think there should be 1 parameter like ```renderingStrategy``` (bad name actually) with 3 options:
1) render one
2) renders siblings
3) render all
But we really should think about meaningfull names 😄 What do you think?

**Comment by knowbody** [comment]
@cctuan thank you for working on it!

**Comment by cctuan** [comment]
@skv-headless 
Thanks for your advice .
I'm thinking using prerenderingSiblings as number type ,
0 means only render current page , and 1 means render nearby 1 sibling and Infinity means means render all.

What do you think ?

@knowbody  you're welcome . I need this too.

**Comment by skv-headless** [comment]
@cctuan great name 👍 . Don't you think that ```prerenderedSiblingsNumber``` would be better name?

**Comment by cctuan** [comment]
@skv-headless  updated ! Thanks.

**Comment by skv-headless** [comment]
Great work. Thanks.

**Pull request merged**
