### PR TITLE
Fix old react native view proptypes api (undefined ViewPropTypes)

### PR DESCRIPTION
**Pull request by terrysahaidak**
Tried with my project. Works as expected.

Try it out https://github.com/JSSolutions/GitterMobile

### CODE REVIEW

**Comment by kentosasa** [comment]
Thanks! it was good for me.

**Comment by terrysahaidak** [comment]
Could anybody look at that?

**Comment by wilomgfx** [comment]
This needs to be merged ASAP. Unusable if not fixed.

**Comment by wilomgfx** [comment]
@skv-headless This needs to be merged.

**Comment by wilomgfx** [comment]
This is broken with react native 0.42+... please merge it asap!

**Comment by skv-headless** [comment]
It is new API since react-native 0.45. If I use older version just downgrade to previous version.

**Comment by wilomgfx** [comment]
@skv-headless my current project is on 0.42, and it brakes so...

**Pull request closed without merging**
