### PR TITLE
back to viewPagerAndroid

### PR DESCRIPTION
**Pull request by vonovak**
unfortunately scroll view on android doesn't work with RefreshControl, so this PR brings viewPagerAndroid back

### CODE REVIEW

**Comment by skv-headless** [comment]
I can't do it. There are few bugs with ViewPager. Lets try to solve it. For example make an issue in react-native repository.

**Comment by vonovak** [comment]
@skv-headless what kind of bugs do you mean? thanks

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/issues?q=is%3Aopen+is%3Aissue+label%3Anested

**Comment by skv-headless** [comment]
@vonovak https://github.com/skv-headless/react-native-scrollable-tab-view/issues/179#issuecomment-192723122 does it work for you?

**Comment by skv-headless** [comment]
I'll close for now. If it would be needed I'll make revert commit. Thank you for bug report.

**Pull request closed without merging**
