### PR TITLE
support scrollTabBar mask

### PR DESCRIPTION
**Pull request by WaterEye0o**
Effect as shown：
scrollable_example

You can see a layer of mask on scrollTabBar left and right

### CODE REVIEW

**Comment by skv-headless** [comment]
Thank you for pr. I'm trying to follow https://material.io/guidelines/components/tabs.html guide. Such feature doesn't described there but you can create example in separate repository where we can pick tab bar with such effect and I will put link in readme. I think it would be cool

**Comment by WaterEye0o** [comment]
@skv-headless This is the repository I created,and its github address is https://github.com/WaterEye0o/react-native-scrollable-tab-mask-view,npm address is https://www.npmjs.com/package/react-native-scrollable-tab-mask-view .please put it in your readme

**Comment by skv-headless** [comment]
Actually I expected that people could use it as custom tab bar like here https://github.com/skv-headless/react-native-scrollable-tab-view#injecting-a-custom-tab-bar .

**Comment by WaterEye0o** [comment]
@skv-headless  sorry,I understand the wrong. this is  my re-create the repository.https://github.com/WaterEye0o/react-native-scrollable-tab-view-mask-bar

**Pull request closed without merging**
