### PR TITLE
Add new prop `tabBarElevation` for the tabBar's elevation

### LINKED ISSUE #276: Allow Passing in Elevation to TabBar Style if tabBarPosition==='top'
For example something like:
```js
if (this.props.tabBarElevation) {
   tabBarProps.style = {...(tabBarProps.style || {}), elevation: this.props.tabBarElevation};
}
```

### PR DESCRIPTION
**Pull request by cancan101**
Closes #276

### CODE REVIEW

**Comment by skv-headless** [comment]
Tabbars have ```style``` property where you can pass ```elevation```. Why don't you like such approach?

**Comment by cancan101** [comment]
Where / how? I don't see this.

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/SimpleExample.js#L10

**Comment by cancan101** [comment]
Isn't that for the whole container ie including the content? In the case of
elevation the shadow appears on the bottom of the screen rather than below
the tabs.

**Comment by skv-headless** [comment]
Sorry. My fault. That should work
```<ScrollableTabView renderTabBar={() => <ScrollableTabBar style={{elevation: 1}}/>}>```

**Comment by skv-headless** [comment]
@cancan101 does my solution work for you?

**Comment by cancan101** [comment]
Yes, that works.

**Comment by skv-headless** [comment]
cool

**Pull request closed without merging**
