### PR TITLE
Update ScrollableTabBar.js

### PR DESCRIPTION
**Pull request by iwgang**
Platform === 'android'   to Platform.OS === 'android'

### CODE REVIEW

**Comment by skv-headless** [comment]
I think we can remove this condition and leave only ```this._scrollView.scrollTo({x: newScrollX, y: 0, });```

**Comment by iwgang** [comment]
No problem

**Comment by skv-headless** [comment]
Are you going to do this?

**Comment by iwgang** [comment]
^ ^ . You submit it..

**Pull request closed without merging**
