### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pedramsaleh**
To clarify support for more than 5 tabs.

### CODE REVIEW

**Comment by skv-headless** [comment]
Could you please add example as https://github.com/brentvatne/react-native-scrollable-tab-view#basic-usage ?

**Comment by pedramsaleh** [comment]
OK, example added.

**Comment by skv-headless** [comment]
@pedramsaleh sorry that I'so annoying. As I see it:
here are few examples https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabsExample.js . 

I want to see in README a gif image to see how it works and just link to an example.

**Comment by pedramsaleh** [comment]
I don't have software to make a GIF image.  I just wanted to make it easier for others and provide a clear way for how to have extra tabs scrolling off to the side, since I didn't see that back when it was first implemented, and had to basically figure it out on my own.

**Comment by skv-headless** [comment]
Now there is demo in browser I think it would be enough to figure out when to use scrollable  tab bar.
https://github.com/skv-headless/react-native-scrollable-tab-view#demo

**Pull request closed without merging**
