### PR TITLE
Update to React 15.0.2, React-Native 0.26.3, Ionicons 2.0.3

### PR DESCRIPTION
**Pull request by akoshman**

### CODE REVIEW

**Comment by skv-headless** [comment]
Have you done react-native upgrade ? I saw some changes there

**Comment by skv-headless** [comment]
Thanks btw. I realy appreciate that work 👍

**Comment by akoshman** [comment]
@skv-headless 
What do you mean by "react-native upgrade"?
I only updated the example project to use the newest libraries. The core **react-native-scrollable-tab-view** module worked well with updated libraries, there were issues only with the example. However, I only tested it on Android emulator and device.

**Comment by skv-headless** [comment]
https://facebook.github.io/react-native/docs/upgrading.html#2-upgrade-your-project-templates . It updates react-native native(obj-c, java) code. Usually it is very painful. I will do it by myself if you don't have time

**Comment by skv-headless** [comment]
fixed here https://github.com/skv-headless/react-native-scrollable-tab-view/commit/aba5c918c8074f61cda340456ae9d6449e018d27

**Pull request closed without merging**
