### PR TITLE
Make the Tab Button TouchHighlight for Android borderless like in the Twitter App

### PR DESCRIPTION
**Pull request by mortik**
screenshot 2016-07-19 13 05 401

### CODE REVIEW

**Comment by skv-headless** [comment]
Sorry for delay 😔 . Could you please make a gifs before and after?

**Comment by mortik** [comment]
Sure here you go :)

**Before**
tab-android-click-before mov

**After**
tab-android-click-after mov

**Comment by skv-headless** [comment]
👍 I like it more. Could you please rebase your commit?

**Comment by mortik** [comment]
done :)

**Pull request merged**
