### PR TITLE
Potential fix for tab content not appearing in a ScrollView

### PR DESCRIPTION
**Pull request by crozzfire**
Takes out `<ViewPagerAndroid>` entirely. #187

### CODE REVIEW

**Comment by skv-headless** [comment]
Basically this component is android pattern build on top of ```ViewPager``` and for iOS I'm just trying to make ScrollView behave like ```ViewPager```. As I know scrollview for android doesn't support paging and probably many other properties. If it is working for android could you please make a video?
Also can you give me a link to react-native issue about this problem?

**Comment by holyxiaoxin** [comment]
When it's inside a ScrollView, There is no children view. Clicking on the tab is requires 2 clicks to get the underline in the correct position (delayed by 1 state update).

I've tried this and it's working.

**Comment by holyxiaoxin** [comment]
@skv-headless this issue is still opened. Can we take a look at this? Thanks.

**Comment by skv-headless** [comment]
There should be a reason why in android there is a separate component like ```ViewPager```. I'm still thinking. Please don't judge me on this.

**Comment by walidvb** [comment]
Added a very similar PR that makes the use of `ViewPagerAndroid` optional

**Comment by skv-headless** [comment]
Please try version from master. Feedback would be welcome. Hope there won't be bugs.

**Pull request closed without merging**
